version: '3.7'

services:
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: chatify
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6-alpine

  rabbitmq:
    image: rabbitmq:3-management-alpine

  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 chatify.wsgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
      - rabbitmq
    environment:
      DATABASE_URL: postgres://user:password@db:5432/chatify
      REDIS_URL: redis://redis:6379/0
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/

volumes:
  postgres_data:
